USE `stockboard`;
INSERT INTO stocks_meta (symbol, name_en, name_zh, short_name_en, short_name_zh, twse_symbol) VALUES
('AAPL','Apple Inc.','蘋果公司','Apple','蘋果',NULL),
('AMGN','Amgen Inc.','安進公司','Amgen','安進',NULL),
('AXP','American Express Company','美國運通公司','American Express','美國運通',NULL),
('BA','The Boeing Company','波音公司','Boeing','波音',NULL),
('CAT','Caterpillar Inc.','卡特彼勒公司','Caterpillar','卡特彼勒',NULL),
('CRM','Salesforce, Inc.','賽富時公司','Salesforce','賽富時',NULL),
('CSCO','Cisco Systems, Inc.','思科系統公司','Cisco','思科',NULL),
('CVX','Chevron Corporation','雪佛龍公司','Chevron','雪佛龍',NULL),
('DIS','The Walt Disney Company','華特迪士尼公司','Disney','迪士尼',NULL),
('GS','The Goldman Sachs Group, Inc.','高盛集團','Goldman Sachs','高盛',NULL),
('HD','The Home Depot, Inc.','家得寶公司','Home Depot','家得寶',NULL),
('HON','Honeywell International Inc.','霍尼韋爾國際公司','Honeywell','霍尼韋爾',NULL),
('IBM','International Business Machines Corporation','國際商業機器公司','IBM','IBM',NULL),
('INTC','Intel Corporation','英特爾公司','Intel','英特爾',NULL),
('JNJ','Johnson & Johnson','嬌生公司','Johnson & Johnson','嬌生',NULL),
('JPM','JPMorgan Chase & Co.','摩根大通','JPMorgan Chase','摩根大通',NULL),
('KO','The Coca-Cola Company','可口可樂公司','Coca-Cola','可口可樂',NULL),
('MCD','McDonald''s Corporation','麥當勞公司','McDonald''s','麥當勞',NULL),
('MMM','3M Company','3M公司','3M','3M',NULL),
('MRK','Merck & Co., Inc.','默克公司','Merck','默克',NULL),
('MSFT','Microsoft Corporation','微軟公司','Microsoft','微軟',NULL),
('NKE','NIKE, Inc.','耐吉公司','NIKE','耐吉',NULL),
('PG','The Procter & Gamble Company','寶僑公司','P&G','寶僑',NULL),
('TRV','The Travelers Companies, Inc.','旅行者保險公司','Travelers','旅行者',NULL),
('UNH','UnitedHealth Group Inc.','聯合健康集團','UnitedHealth','聯合健康',NULL),
('V','Visa Inc.','威士公司','Visa','威士',NULL),
('VZ','Verizon Communications Inc.','威瑞森通訊公司','Verizon','威瑞森',NULL),
('WBA','Walgreens Boots Alliance, Inc.','沃爾格林聯合博姿公司','Walgreens','沃爾格林',NULL),
('WMT','Walmart Inc.','沃爾瑪公司','Walmart','沃爾瑪',NULL)
;